# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77c2708ef1201d5da8ed0a9ee4e4b5ba0816a54510a5f642aa8a8c68ce8d59a344829db7ecc6eba675d38f3f93e5ca550b27e0f93e67877cf1eca85a619a0ffb

test:
  secret_key_base: 58b274c13f70c47e0245156bd87d6d55d2a7194b7e71cb120c4891918d3df3278c366114f2a2b1b0a176aad7db101aa12e6c3c894aea8c3fae3ddf2c747e1f9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
